<main class="main-acc">
    <div class="insert-ad-coul">
        <form method="post" class="form-edit">
            <h2>éditer une principe actif</h2>
            <label for="principe">principe actif</label><br>
            <input type="text" name="principe" id="principe" value="<?= $principe->getPrincipeActif() ?>" />
            <button type="submit" class="save">Modifier</button>


        </form>
    </div>
</main>