<?php $session = new SessionVerify() ?>
<!doctype html>

<html lang="fr">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="assets/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Accueil du site</title>
</head>

<body>

    <header>
        <nav>
            <div class="nav-top">
                <h1><a class="titre" title="lien accueil et titre" href="index.php?controller=accueil&action=index">Toxiplante</a></h1>


                <a class="atop" title="lien page couleur" href="index.php?controller=couleur&action=index">couleur</a>

                <a class="atop" title="lien page familles" href="index.php?controller=famille&action=index">famille</a>

                <a class="atop" title="lien page principe actifs" href="index.php?controller=principe&action=index">principe actif</a>

                <hr>
            </div>

        </nav>
    </header>
  

    <?php include_once $vue ?>


    <footer>

        <nav class="nav-bot">
            <?php if ($session->isAdmin()) : ?>


                <div class="botdiv">
                    <a class="deco" title="deconnexion" href="index.php?controller=connexion&action=logout">déconnexion</a>

                    <a class="abot" title="lien page admin couleur" href="index.php?controller=couleur&action=admin">admin couleur</a>


                    <a class="abot" title="lien page admin famille" href="index.php?controller=famille&action=admin">admin famille</a>


                    <a class="abot" title="lien page admin principe" href="index.php?controller=principe&action=admin">admin principe</a>


                    <a class="abot" title="lien page admin plante" href="index.php?controller=plante&action=admin">admin plante</a>
                </div>


            <?php else : ?>
                <div>
                    <div class="botdiv">
                        <a class="conn" title="lien page connexion" href="index.php?controller=connexion&action=index">page de connexion</a>
                    </div>
                </div>
            <?php endif ?>
        </nav>


    </footer>
</body>

</html>