<main>


    <h2 class="titre-conn">page de connexion admin</h2>
    <p class="titre-conn">connexion seulement disponible pour la moderatrion</p>
    <fieldset class="form-conn">

        <form action="index.php?controller=connexion&action=index" method="post">
            <div>
                <label for="email">mail :</label>
                <input type="email" name="email" id="email">
            </div>

            <div>
                <label for="passwrod">mot de passe :</label>
                <input type="password" name="password" id="password">
            </div>


            <button id="send" type="submit">Se connecter </button>

        </form>
    </fieldset>
</main>